### ISSUE TITLE
`packetToEncodedVideoChunk` accidentally ignores `timeBaseSrc` value

### ISSUE THREAD

**Issue by jyeokchoi** [Yahweasel/libavjs-webcodecs-bridge#11]
Hello, Thank you for your amazing work 🙂 

I've noticed that some video packet timestamps appear broken.
They seem to ignore the `timeBaseSrc` values.

I'm suspecting that [this commit](https://github.com/Yahweasel/libavjs-webcodecs-bridge/commit/ab6beff5c8f58f5b7c86fa5c54511d1430712832#diff-666cc10e0248a3dc7a4cbe9f27c974eb3b1a5910d8dd775155bb1cd043f5e17cR432) introduces a fallback value of `1` to the `tbNum`, making the following `if(!tbNum)` clause unreachable.

Could you take a look at this?

Thank you!

**Comment by Yahweasel** [comment]
Yeah, you're quite right. When I made it strict mode, I avoided the undefinedness issue in an incorrect way :(

Thanks!
