### ISSUE TITLE
`videoStreamToConfig` does not work for h264/annexB streams

### ISSUE THREAD

**Issue by reinhrst** [Yahweasel/libavjs-webcodecs-bridge#2]
The [spec states](https://www.w3.org/TR/webcodecs-avc-codec-registration/#videodecoderconfig-description): 

>If the [description](https://www.w3.org/TR/webcodecs/#dom-videodecoderconfig-description) is present, it is assumed to be an AVCDecoderConfigurationRecord, as defined by [[iso14496-15]](https://www.w3.org/TR/webcodecs-avc-codec-registration/#biblio-iso14496-15), section 5.3.3.1, and the bitstream is assumed to be in [avc](https://www.w3.org/TR/webcodecs-avc-codec-registration/#dom-avcbitstreamformat-avc) format.
> If the [description](https://www.w3.org/TR/webcodecs/#dom-videodecoderconfig-description) is not present, the bitstream is assumed to be in [annexb](https://www.w3.org/TR/webcodecs-avc-codec-registration/#dom-avcbitstreamformat-annexb) format.

So as I understand it, for files in AnnexB format `videoStreamToConfig` should return an empty `description`.
My test video indeed works if I add a `config.description = undefined` after the `videoStreamToConfig` call.

**Comment by Yahweasel** [comment]
Do you have an example file or instructions for making one? In my tests, a file in annexb format also didn't have extradata, so it didn't trigger a description in the config.

**Comment by reinhrst** [comment]
Sure:
https://www.dropbox.com/scl/fi/chpaiw8mr05sn9w9kek5z/video-annexb.MTS?rlkey=d1ae1ma9xk0642kgeui8o3qkt&dl=0

Gives me in the `config.description`:
```
00 00 10 67 64 00 28 ad d3 a4 62 b6 64 42 14 d4 9d 23 15 94 c4 44 29 a9 3a 46 2b 29 88 88 53 43 40 69 4c dc 89 11 9a 20 85 a2 18 a5 28 82 10 85 11 10 42 d1 c0 52 94 41 80 42 88 8c 33 22 46 6d 99 24 8c db 6d 24 92 44 6d b6 56 44 92 44 b6 db 49 11 5b 64 49 32 42 44 69 48 ed 25 4a ee aa 94 8e ed c9 55 4a dd 91 55 5d 24 99 d0 3b 10 e0 11 1f 78 80 80 00 00 30 00 80 00 00 19 74 a0 00 20 6c 80 10 39 42 80 70 71 62 91 60 00 00 00 10 68 ea 41 f2 c0 00
```

(libav.js sha 83ceadd53f92cbdb6048bc0ca4d29591eacdd158; custom config: `["demuxer-ogg", "demuxer-mp4", "demuxer-mov", "demuxer-opus", "demuxer-matrosha", "demuxer-web      m", "parser-h264", "decoder-h264", "muxer-mp4", "demuxer-mpegts", "cli"]`

Let me know if you need any more info

**Comment by Yahweasel** [comment]
That commit should fix this, but if you have any files for which it doesn't work, please reopen.

**Comment by reinhrst** [comment]
so far it works on all my annexb files :)
