### ISSUE TITLE
demo can not run

### ISSUE THREAD

**Issue by nbutmickey** [Yahweasel/libavjs-webcodecs-bridge#4]
i use a h.264 video, devtool console here
<img width="1354" alt="image" src="https://github.com/Yahweasel/libavjs-webcodecs-bridge/assets/30484035/b3a5d387-92cf-45c9-89c4-16393d646b3e">

**Comment by Yahweasel** [comment]
You have not compiled libavjs-webcodecs-bridge. You need to compile it with `make` first, or use the release from npm.
