### ISSUE TITLE
Why are negative pts values forced to 0?

### ISSUE THREAD

**Issue by reinhrst** [Yahweasel/libavjs-webcodecs-bridge#5]
See https://github.com/Yahweasel/libavjs-webcodecs-bridge/blob/98fb137f2b06029e376dc252c31d2f0b540a5919/src/demux.ts#L415

I have some files that were converted from MTS to  MP4 using ffmpeg. One of the things that seems to happen is that ffmpeg readjusts the pts and dts, so that the first key-frame had `pts = 0`. As a result, the two B frames right after this frame have negative pts values. They also have the [AV_PKT_FLAG_DISCARD](https://ffmpeg.org/doxygen/trunk/group__lavc__packet.html#ga3d36105d7143b319acef3c86d2beb382) set (since they would need the last P frame from before the stream started to be able to decode). All three first frames have negative dts values as well.

I was wondering if there was a reason to force negative pts values to 0 here, or if it was just done because the `ptslo + 0x100000000 * psthi` doesn't quite work for negative values?

**Comment by Yahweasel** [comment]
Yeah, that math _really_ doesn't work for negative values. `ptshi` is -1 for all reasonable negative values, so this ends up as -0x100000000 minus the correct value, which is a wild timestamp. When writing this I anticipated that problem but couldn't quickly think of the mathematically correct way to get the bitwise behavior I wanted, so I just truncated it. If you know the right math (given that `<< 32` doesn't work), feel free to fix it ^^´

**Comment by reinhrst** [comment]
So the super-delux with stars solution would be (I think):

```ts
    const view = new DataView(new ArrayBuffer(8))
    view.setInt32(0, lo, true)
    view.setInt32(4, hi, true)
    return Number(view.getBigInt64(0, true))
```

It should work on all platforms, regardless of endianness, and without any magic.

Assuming you know you're little endian, you can use the oneliner

```ts
return Number(new BigInt64Array(new Int32Array([lo, hi]).buffer).at(0))
```

Using plain old javascript, the trick is to convert the "lo" to an unsigned int; then the formula just works

```ts
    const unsigned_lo = lo >= 0 ? lo : lo + 0x100000000
    return hi * 0x100000000 + unsigned_lo
```

or if you like more bit-magic
```ts
    const unsigned_lo = lo + (lo & 80000000) * 2
    return hi * 0x100000000 + unsigned_lo
```

This assumes that the numbers stay under MAX_SAFE_INT, math says that MAX_SAFE_INT will give you 285 years in microseconds (and more in 90k ticks), so that should be fine.

Actually I think that the current code will break anyways at `2^31 < pts < 2^32`, since `lo` would be negative then, being 32bit signed int -- something that happens after about 6.5 hours of video with tbn = 90k.

**Comment by reinhrst** [comment]
To check that it works, see [this playground](https://www.typescriptlang.org/play?target=9&ssl=15&ssc=42&pln=14&pc=5#code/GYVwdgxgLglg9mABAZwA4BsZQBRhAWwC5EAjGAcxjCgEpiBtPfEgUwCcAaRJ1tgXUQBvAFCIxiCAmRREANxgsA7ogC83JYgBCFAJLUAbABYAgmzYBDAJ7ZGBPjVHjJYaXIWKAzACZV65XqhvUwtreSUAOhIQYGB2B0cxNhYoEDYkejDPL3DzHAAGGgBCLkzvHJwARiK+YQBfYWFQSFgECThmKhZsdDhiHnYuAAsYPoJeOm4x9iEEtpcZTN8wDQARXPMANXdcDWCrTWjYtmwADhoHcTcI5GSA72w8rh6uKDYQFgvxTPCbqDuvbCGIYwF5vD6zAD0EKSKTSiAAclNjt9yMltOQAkYHqD3udIdDkqkkIjmOwdsp0ZiTGYrOTEP89tZ6M9EMN7JFDnFyg88ZdnK5wMgKMsACYAfR6vklAGpEN04IgAGSIE55NXqgqIABUiC8sxhRNZMG1iDyAA8KhqNYhZYLhSxxT06g0mtB4Eg0JgoMYwCKAMLtMjLXAEYhkSjUGgzPlSGTMuDAgRqT1YEP4T5iflwdAscI9cjYAAGJN4iAAJIImLUUBgsMhEFAFT0VBWetXzL6jS3BMNaoWM3NXJJmL5h0GuizhgOszm83AC4WAx1RQ3hvWYPWK2O+9PY6QKEuSL5KdRsGPd-NECKYDFfOHD4gALSTfCzGe5-NFlY34CIDflwRrxiWoAG4X1Lf8KxLdhwg3ABlcxYgCFhUWOc9EAAfkQAAibDEGIbCwDgKBsPbFBEJYP9qH7Z1hBTb1fUPToHgtPIwAceifX9QNmPNPI-StNV2Lo2sGO45cunNABWQShI40SuKY4NH3NS1hM4xieOUviBME9SFM0iTsBUs0ZNk4ThCAA)

**Comment by Yahweasel** [comment]
Re the dataview method, we can always assume we're little-endian, because Emscripten does. Emscripten-compiled code does not work on big-endian systems. But, I'd still prefer not to go that route because of bigints.

I think the rightest solution is to integrate to-64-from-64 functions into libav.js itself (since it's causing the problems :) ), and then use that from the bridge and everywhere else.

**Comment by reinhrst** [comment]
> Re the dataview method, we can always assume we're little-endian, because Emscripten does. Emscripten-compiled code does not work on big-endian systems. But, I'd still prefer not to go that route because of bigints.

That makes sense; it you're going to support bigints, you might as well [have the parameters be bigints from the start](https://emscripten.org/docs/getting_started/FAQ.html#how-do-i-pass-int64-t-and-uint64-t-values-from-js-into-wasm-functions).

**Comment by reinhrst** [comment]
This split in hi/lo is happening in 3 places in `libavjs`: `interface Frame`, `interface Packet` and the 4 types of `avformat_seek_file`. Maybe the nicest solution would be to abstract all this away inside those places:

- `Packet` will get an extra field `pts_unsafe` or `pts_safeint` or something TBD[^1], same for `dts` and `duration`
- `Frame` will get an extra field `pts_unsafe` or `pts_safeint` or something TBD[^1]
- Four new `avformat_seek_file_safeint*` functions will be created, that take a single numbers per parameter. Same naming issue applies here. Being a large proponent of defensive programming, I think these should throw if not `MIN_SAFE_INT <= num <= MAX_SAFE_INT`

This will add a couple of cycles to each place where packets and frames are returned, but I imagine that the person who really cares about top performance, will use pointer-returns anyways from these functions.

(just thinking out loud; we could also define a new copyout method that just returns `pts` (no `ptshi`), which throws an error if not in SAFE_INT range. At some point in the future (e.g. major release), it could be decided to make this method the default.)

As a side story: I spent a good couple of hours when I started this project googling what the *** `ptshi` and `dtshi` values were, and only after a long long time I figured out that they're decomposed int64s (in my mind I read them as `pt-shi` and `dt-shi`, which didn't help). Taking them away at all for all but the power-dest of power users might mean less searching for others (or else maybe this issue will turn up on Google :)).

[^1]: I don't have a good suggestion for the name. It's the field that you probably would like most people to use (so calling it "unsafe" doesn't sound right), but you also want to stress that in extreme situations you need to use the `pts` and `ptshi` fields (calling it `safeint` suggests that this is the safe one). Maybe nicest would be have `pts`, `ptslo` and `ptshi`, but this would be a breaking change....

**Comment by reinhrst** [comment]
OK, my search was not exhaustive..... Other places where this is used:

- `AVCodecContextProps` for `bit_rate`, `rc_max_rate`, `rc_min_rate`
- The functions `AVStream_duration`, `AVPacket_duration`, `AVPacket_dts`, `AVPacket_pts`, `AVCodecContext_rc_min_rate`, `AVCodecContext_rc_max_rate`, `AVCodecContext_channel_layout`, `AVCodecContext_bit_rate`, `AVFrame_pts`, `AVFrame_channel_layout` -- they all have a `hi` companion, and a `set` variant

I _think_ that the same trick of abstracting this away as long as it's within the safe int range, should work; and all of them look like they should not often exceed MAX_SAFE_INT (with the possible exception of `channel_layout`, which I don't really know how it works, but might be a bitmask).

**Comment by Yahweasel** [comment]
channel_layout is a bitmask, yes. You can simply treat its high and low bits as independent bitmasks; no need for conversion. (In practice, you can simply treat its low bits as the layout and call it a day)

My inclination is not towards anything so complicated. I don't want to break backwards compatibility over huge timestamp values, and I don't want to perform this conversion back and forth when much of the time it's not used at all. I've added `i64tof64` and `f64toi64` functions to libav.js, and IMO, that's sufficient (along with changing the client code in libavjs-webcodecs-bridge and libavjs-webcodecs-polyfill to use it, of course). Perhaps I should've named it "ptslo" in the first place to siren users to think about it, but hindsight is 20/20.

The -hi variables could definitely use more documentation :) . pt-shi ("pt is" in Mandarin!) is not an ideal misinterpretation :)

**Comment by Yahweasel** [comment]
(By the way, the reason libav.js doesn't use bigints from the start isn't *just* that I'm trying to keep it as broadly compatible as possible. It's also because libav.js predates bigints.)

**Comment by reinhrst** [comment]
> (By the way, the reason libav.js doesn't use bigints from the start isn't _just_ that I'm trying to keep it as broadly compatible as possible. It's also because libav.js predates bigints.)

It's hard to remember how recent Javascript was quite happy to ignore that 64 bit ints existed :)..

I also think that bigint is a bit slower than native number, but not 100% sure...
