### ISSUE TITLE
demo issue with aac

### ISSUE THREAD

**Issue by 369-jas** [Yahweasel/libavjs-webcodecs-bridge#7]
I have a video file I'm trying to run with the demo. However, it seems like the audio stream is always skipped.

I tried to track this down and it seems like in libavjs-webcodecs-bridge.js for audioStreamToConfig, the codecString is 'aac', but the profile is -99, so the returned config ends up being null. However if I manually set the profile to 1 in that function, then the demo works.

I was going to rebuild libavjs to track this down, but was running into issues and wondered if you might have any ideas here.

ffprobe on my video file:
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '../../annie.mp4':
  Metadata:
    major_brand     : qt
    minor_version   : 0
    compatible_brands: qt
    creation_time   : 2024-06-17T03:50:11.000000Z
  Duration: 00:03:09.69, start: 0.000000, bitrate: 2401 kb/s
  Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 248 kb/s (default)
      Metadata:
        creation_time   : 2024-06-17T03:50:11.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709, progressive), 640x360, 2148 kb/s, 23.98 fps, 23.98 tbr, 24k tbn (default)
      Metadata:
        creation_time   : 2024-06-17T03:50:11.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : H.264

**Comment by 369-jas** [comment]
I figured out how to build things, so I will continue see if I can figure out what's happeniing

**Comment by J3698** [comment]
It seems like for whatever reason profile is set to FF_PROFILE_UNKNOWN (-99), but it seems I can parse extradata to see if codec should be AAC LE or HE, so I'm doing that for now

**Comment by Yahweasel** [comment]
Interesting. The AAC parser must not be detecting the profile for some reason. In my experience, the WebCodecs decoders don't *actually* care. Does it work if you set it to some obvious value, even if it's not right?
